FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY package*.json ./

RUN apt-get update
RUN apt-get install npm ffmpeg -y
RUN npm i npm@latest -g
RUN npm install --yes

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN npm run build

EXPOSE 80

CMD [ "python", "serve.py" ]