version: "3.8"
services:
    lecture-downloader:
        build: .
        # environment:
        #     - VIRTUAL_HOST=lectures.aidandev.ca
        ports:
            - "80:80"
        restart: unless-stopped
        network_mode: "bridge"