version: "3.8"
services:
    hss-solver:
        build: .
        # environment:
        #     - VIRTUAL_HOST=lectures.aidandev.ca
        ports:
            - "5000:80"
        restart: unless-stopped
        network_mode: "bridge"